# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:titLe/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: Hellebusch Recipes
tagline: 'Hellegood Recipes'
description: 'Hellebusch family/favorite recipes.'
keywords: 'food, recipes'
url: https://hellebusch.recipes
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Sean Hellebusch
  image: author
  url: https://hellebusch.io
  email: sahellebusch@gmail.com

social:
  github: https://github.com/sahellebusch

version: 2.0.0

github:
  repo: https://github.com/sahellebusch/hellebusch.recipes

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

google_analytics_key: UA-37412525-4
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/sahellebusch/hellebusch.recipes

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
