#!/bin/bash

RECIPE=$1
echo Making new recipe template for "$RECIPE"
git checkout -b $RECIPE

echo "---
title: Recipe Title
ref: $RECIPE
image: true
time: 45
category: dinner
tags: [salad, kale, greens, dinner]
ingredients:
  - name: sweet potatoes, cut in 1/2 inch circles
    amount: 2 small
    unit: 
---

1. Step 1!
2. Step 2!

<br>
### *Notes:*
- Add recipes nots here

_From [Half Baked Harvest](https://www.halfbakedharvest.com/kale-caesar-salad/)._
" >>  _recipes/$RECIPE.md

cp temp.jpg _images/posts/$RECIPE.jpg

read -p "Replace the new image at _images/posts/$RECIPE.jpg and press enter"

npm run build
jekyll serve